"""add_to_node_id_to_comments

Revision ID: 351313c224f9
Revises: 3899adfca211
Create Date: 2026-03-15 16:49:24.092726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351313c224f9'
down_revision: Union[str, Sequence[str], None] = '3899adfca211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('to_node_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'to_node_id')
    # ### end Alembic commands ###
